# Port number to be bind
port-number: 8888

# Secret for webhook
# Change this when deploying
web-secret: "12345"

# Path to database file for history
# Change this when deploying
db-file: /tmp/ci.sqlite3

# Path to log file for the server
log-file: /tmp/ci.log

# Github Token
github-token: "<TOKEN>"
