name: Build & Deploy Docs

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Docs with Maven
      run: mvn site

    - id: stack
        uses: freckle/stack-action@v5
        with: 
          working-directory: ./server
        
    - name: Build Docs with haddock
      run: cd server && stack haddock

    - name: Copy Docs to site
      run: cd server && cp -r "$(stack path --local-doc-root)" ../target/site

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: docs
        publish_dir: ./target/site
        force_orphan: true
