name: Check Coding Style

on:
  push:

jobs:
  java-style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Spotless
      run: mvn spotless:check

  haskell-style:
    runs-on: ubuntu-latest

    steps:
    - uses: haskell-actions/run-fourmolu@v9
      with:
        # Use fourmolu-0.13.0.0.  If you don't specify this, then the latest
        # release of fourmolu will be used.
        version: "0.13.0.0"
